- hosts: kube
  become: yes
  gather_facts: no
  tasks:

    - name: Install docker
      package:
        name: docker.io
        state: present
    
    - name: Enable and start docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Check if swap is turned on
      shell: free -m | grep Swap | awk '{print $2}'
      register: swap_check
      changed_when: no

    - name: Turn off swap
      shell: swapoff -a  
      when: swap_check.stdout != 0

    - name: Disable swap
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'
      when: swap_check.stdout != 0


    - shell: modprobe br_netfilter
    
    - copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          br_netfilter
    
    - copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
    
    - shell: sysctl --system

    - package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
        state: present

    - shell: curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg

    - name: Add Kubernetes apt repository
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
        apt update

    - name: Install Kuiberneties Packages
      package:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Prevent Kubernetes package upgrades
      shell: apt-mark hold kubelet kubeadm kubectl
    

