- hosts: monitored_hosts
  become: yes
  gather_facts: no
  roles:
    - { role: elastic_metricbeat, restart_service: yes }
    - { role: elastic_filebeat, restart_service: yes }
    - { role: elastic_packetbeat, restart_service: yes }
  tasks:

  #   - name: Enable metricbeat modules
    - name: Freeswitch monitoring
      block:
        - include_role:
            name: freeswitch
            tasks_from: monitoring
      when: "'freeswitch' in group_names"
  
      
      