- hosts: dhcp_dns
  become: yes
  gather_facts: no
  tasks:
    
    - name: Inlcude private_vars
      include_vars:
        file: private_vars.yml
    

    - name: Copy the Dnsmasq config
      template:
        src: dnsmasq.conf.j2
        dest: /etc/dnsmasq.conf
        validate: dnsmasq --test --conf-file=%s
      notify: restart dnsmasq


    - name: Update /etc/hosts
      blockinfile:
        path: /etc/hosts
        block: |
          192.168.1.24  git


  handlers:
    - name: restart dnsmasq
      service:
        name: dnsmasq
        state: restarted