- hosts: dad
  become: yes
  gather_facts: no
  tasks:
    
    - name: Inlcude vars
      include_vars:
        file: "{{ item }}"
      loop:
        - private_vars.yml
        - dns_dhcp.yml
    

    - name: Copy the Dnsmasq config
      template:
        src: dnsmasq.conf.jinja
        dest: /etc/dnsmasq.conf
        validate: dnsmasq --test --conf-file=%s
      notify: restart dnsmasq


    - name: Update /etc/hosts
      blockinfile:
        path: /etc/hosts
        block: "{{ lookup('template', 'hosts.stub.jinja') }}"
      notify: restart dnsmasq


  handlers:
    - name: restart dnsmasq
      service:
        name: dnsmasq
        state: restarted
