- hosts: dad
  become: yes
  gather_facts: no
  vars:
    dhcp_hostsfile: /etc/dhcp_hosts.conf
  tasks:
    
    - name: Inlcude vars
      include_vars:
        file: "{{ item }}"
      loop:
        - private_vars.yml
        - dns_dhcp.yml
    

    - name: Copy the Dnsmasq config
      template:
        src: dnsmasq.conf.jinja
        dest: /etc/dnsmasq.conf
        validate: dnsmasq --test --conf-file=%s
      notify: restart dnsmasq


    - name: Deploy /etc/lab_hosts
      template:
        src: lab_hosts.jinja
        dest: /etc/lab_hosts
      notify: reload dnsmasq


    - name: Update DHCP hosts file
      template:
        src: dnsmasq_dhcp_hosts.conf.jinja
        dest: "{{ dhcp_hostsfile }}"
      notify: reload dnsmasq


  handlers:
    - name: restart dnsmasq
      service:
        name: dnsmasq
        state: restarted

    - name: reload dnsmasq
      shell: pkill -1 dnsmasq
