- hosts: dhcp_dns
  become: yes
  gather_facts: no
  tasks:
    
    - name: Copy the Dnsmasq config
      copy:
        src: files/dnsmasq.conf
        dest: /etc/dnsmasq.conf
        validate: dnsmasq --test --conf-file=%s
      notify: restart dnsmasq

    - name: Update /etc/hosts
      blockinfile:
        path: /etc/hosts
        block: |
          192.168.1.24  git


  handlers:
    - name: restart dnsmasq
      service:
        name: dnsmasq
        state: restarted