- hosts: dhcp_dns
  become: yes
  gather_facts: no
  tasks:
    
    - name: Copy the Dnsmasq config
      copy:
        src: files/dnsmasq.conf
        dest: /etc/dnsmasq.conf
        validate: dnsmasq --test --conf-file=%s
      notify: restart dnsmasq


  handlers:
    - name: restart dnsmasq
      service:
        name: dnsmasq
        state: restarted