
- name: Add Beats repository key
  apt_key:
    url: "{{ elastic_repo_key }}"
    state: present


- name: Add beats repository
  apt_repository:
    repo: "deb {{ elastic_repo_url }} stable main"
    state: present


- name: Ensure Packetbeat is installed
  apt:
    name: >-
      packetbeat{% if beats_version is defined and beats_version|length>0 %}={{ beats_version }}{% endif %}
    state: present
  notify: restart packetbeat service


- name: Enable the Packetbeat service
  service:
    name: packetbeat 
    enabled: yes
  when: enable_service
