- name: Install Zabbix repository
  apt:
    deb: https://repo.zabbix.com/zabbix/5.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.4-1%2Bubuntu20.04_all.deb

- name: Install zabbix-agent
  apt:
    name: zabbix-agent
    update-cache: yes
    state: present
